/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_csh_advancedprogramming_NDKTest */

#ifndef _Included_com_csh_advancedprogramming_NDKTest
#define _Included_com_csh_advancedprogramming_NDKTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_csh_advancedprogramming_NDKTest
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_csh_advancedprogramming_NDKTest_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
